/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alksystem;
//TxtFechaNacimiento
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HDMS PC
 */
public class estudiante extends javax.swing.JFrame {
      private int idalumno=0;
      private javax.swing.ButtonGroup GrupoSexo;
    /**
     * Creates new form login
     */
    public estudiante(){
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon.png")));
        ListarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RBMasculino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        RBFemenino = new javax.swing.JRadioButton();
        CBXGrado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        CBXSeccion = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtNombres = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Nuevo = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabLista = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 207));

        jLabel5.setFont(new java.awt.Font("Freestyle Script", 1, 24)); // NOI18N
        jLabel5.setText("ESTUDIANTE");

        TxtFecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel3.setText("NACIMIENTO");

        TxtDireccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel4.setText("DIRECCION");

        TxtTelefono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel6.setText("TELEFONO");

        TxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel7.setText("EMAIL");

        TxtPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel8.setText("PASSWORD");

        jLabel9.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel9.setText("GRADO");

        RBMasculino.setBackground(new java.awt.Color(255, 255, 255));
        RBMasculino.setText("MASCULINO");

        jLabel10.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel10.setText("SEXO");

        RBFemenino.setBackground(new java.awt.Color(255, 255, 255));
        RBFemenino.setText("FEMENINO");

        CBXGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel11.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel11.setText("SECCION");

        CBXSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H" }));

        jLabel12.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png")).getImage().getScaledInstance(136,136, Image.SCALE_SMOOTH)));

        jLabel13.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel13.setText("APELLIDO");

        TxtApellidos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtApellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel14.setText("NOMBRE");

        TxtNombres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TxtNombres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TxtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmail))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtTelefono))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtDireccion))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFecha))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtApellidos))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNombres)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RBMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RBFemenino))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CBXGrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBXSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBMasculino)
                            .addComponent(RBFemenino)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CBXGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CBXSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(13, 152, 242));

        Nuevo.setBackground(new java.awt.Color(13, 152, 242));
        Nuevo.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png")).getImage().getScaledInstance(56,56, Image.SCALE_SMOOTH)));
        Nuevo.setActionCommand("ACEPTAR");
        Nuevo.setBorderPainted(false);
        Nuevo.setFocusPainted(false);
        Nuevo.setMaximumSize(new java.awt.Dimension(56, 56));
        Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuevoMouseExited(evt);
            }
        });
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(13, 152, 242));
        regresar.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gob.png")).getImage().getScaledInstance(56,56, Image.SCALE_SMOOTH)));
        regresar.setActionCommand("ACEPTAR");
        regresar.setBorderPainted(false);
        regresar.setFocusPainted(false);
        regresar.setMaximumSize(new java.awt.Dimension(56, 56));
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regresarMouseExited(evt);
            }
        });
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(13, 152, 242));
        BTNEliminar.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        BTNEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BTNEliminar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/erase.png")).getImage().getScaledInstance(56,56, Image.SCALE_SMOOTH)));
        BTNEliminar.setActionCommand("ACEPTAR");
        BTNEliminar.setBorderPainted(false);
        BTNEliminar.setEnabled(false);
        BTNEliminar.setFocusPainted(false);
        BTNEliminar.setMaximumSize(new java.awt.Dimension(56, 56));
        BTNEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNEliminarMouseExited(evt);
            }
        });
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        Registrar.setBackground(new java.awt.Color(13, 152, 242));
        Registrar.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png")).getImage().getScaledInstance(56,56, Image.SCALE_SMOOTH)));
        Registrar.setActionCommand("ACEPTAR");
        Registrar.setBorderPainted(false);
        Registrar.setFocusPainted(false);
        Registrar.setMaximumSize(new java.awt.Dimension(56, 56));
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Cerrar.setBackground(new java.awt.Color(13, 152, 242));
        Cerrar.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        Cerrar.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png")).getImage().getScaledInstance(56,56, Image.SCALE_SMOOTH)));
        Cerrar.setActionCommand("ACEPTAR");
        Cerrar.setBorderPainted(false);
        Cerrar.setFocusPainted(false);
        Cerrar.setMaximumSize(new java.awt.Dimension(56, 56));
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarMouseExited(evt);
            }
        });
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Registrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(regresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(Nuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BTNEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel40.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        jLabel40.setText("LISTA DE ESTUDIANTES");

        TabLista.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        TabLista.setForeground(new java.awt.Color(102, 153, 255));
        TabLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabLista);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx=0;
    int yy=0;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarMouseExited

    private void RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RegistrarMouseEntered

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
        //aqui va lo del login
        //Validación de campos

        if (this.TxtNombres.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar el nombre del Alumno");
            TxtNombres.requestFocus();//rabFocus();
            return ;
        }
        if (this.TxtApellidos.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar apellidos del Alumno");
            TxtApellidos.requestFocus();
            return ;
        }
        if (this.TxtFecha.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar la fecha de nacimiento del Alumno");
            TxtFecha.requestFocus();
            return ;
        }
        if (this.TxtDireccion.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debe Ingresar la Direccion Del Alumno");
            TxtDireccion.requestFocus();
            return ;
        }
            if (this.TxtTelefono.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar el telefono del Alumno");
            TxtTelefono.requestFocus();
            return ;
        }
            
            if (this.TxtEmail.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar el Email del Alumno");
            TxtEmail.requestFocus();
            return ;
        }
            if (this.TxtPassword.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar el password de acceso al sitema");
            TxtPassword.requestFocus();
            return ;
        }
            
        Logica.ClsAlumno alumno=new Logica.ClsAlumno();  //objeto tipo alumno
        alumno.idalumno=this.idalumno;
        alumno.nombres=this.TxtNombres.getText();
        alumno.apellidos=this.TxtApellidos.getText();
        alumno.direccion=this.TxtDireccion.getText();
        alumno.telefono=this.TxtTelefono.getText();
        alumno.email=this.TxtEmail.getText();
        alumno.password=this.TxtPassword.getText();
        //alumno.fechaNacimiento=this.TxtFecha.getText();
        alumno.fechaNacimiento="01 jun 97";
        if (this.RBMasculino.isSelected()){alumno.sexo="Masculino";}
        if(this.RBFemenino.isSelected()){alumno.sexo="Femenino";}
        //Selecciona el item
        int seleccionado=CBXGrado.getSelectedIndex();
        alumno.grado=(String)this.CBXGrado.getItemAt(seleccionado);//texto del Item seleccionado

        int seleccionado2=CBXSeccion.getSelectedIndex();
        alumno.seccion=(String)this.CBXSeccion.getItemAt(seleccionado);
        //Evaluamos si el usuario esta Registrando una nueva alumno o esta actualizando
        if(this.idalumno==0){
            boolean respuesta=true; //bandera
            respuesta=alumno.RegistrarAlumno(); //ejecuta el método que registra alumno
            ListarAlumnos(); //actualiza la tabla

            //lanza el aviso
            if (respuesta==false)
            {
                JOptionPane.showMessageDialog(rootPane, "Se ha registrado correctamente");
                Limpiarcampos();
                this.BTNEliminar.setEnabled(false);
            }
            else{  JOptionPane.showMessageDialog(rootPane, "Persona No registrada"); }

        }
        else //actualiza los datos de la alumno
        {
            boolean respuesta2=true; //bandera
            respuesta2=alumno.ActualizarAlumno(); //ejecuta el método que Actualiza alumno
            ListarAlumnos(); //actualiza la tabla

            //lanza el aviso
            if (respuesta2==false)
            {
                JOptionPane.showMessageDialog(rootPane, "Se ha Actualizado correctamente");
                Limpiarcampos();
                this.BTNEliminar.setEnabled(false);
            }
            else{  JOptionPane.showMessageDialog(rootPane, "No se actualizó"); }

        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void NuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoMouseEntered

    private void NuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoMouseExited

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
        
        this.Limpiarcampos();
        this.idalumno=0;
        this.BTNEliminar.setEnabled(false);
    }//GEN-LAST:event_NuevoActionPerformed

    private void regresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarMouseEntered

    private void regresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarMouseExited

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        menu MEN = new menu();
         MEN.setAlwaysOnTop( true );
        MEN.setVisible(true);
        int x = (int) rect.getMaxX() - MEN.getWidth();
        int y = 2;
        MEN.setLocation(x, y);
        MEN.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void BTNEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNEliminarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminarMouseEntered

    private void BTNEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNEliminarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliminarMouseExited

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (this.idalumno==0){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un Alumno");
            return;
        }
        //Captura la confirmacion
        int confirmacion= JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro de eliminar?", "Confirma la acción", 2);

        if (confirmacion==0){ //evaluamos la confirmación
            boolean confirmacion2=true;
            Logica.ClsAlumno alum=new Logica.ClsAlumno();
            confirmacion2=alum.EliminarAlumno( this.idalumno);
            if (confirmacion2==false){ //Evaluamos el resultado de la operacion
                JOptionPane.showMessageDialog(rootPane, "Eliminación correcta");
                Limpiarcampos();  //Limpiamos los campos
                this.BTNEliminar.setEnabled(false); //Deshabilitamos el botón
                this.ListarAlumnos(); //recargamos la lista
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se pudo Eliminar");
            }
        }
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void TxtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaActionPerformed

    private void TxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccionActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    private void TxtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidosActionPerformed

    private void TxtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombresActionPerformed

    private void TabListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabListaMouseClicked
    //activa los botones 
       //this.Registrar.setText("Actualizar");
       this.BTNEliminar.setEnabled(true);
        
        //Creación de una fila de JTable y captura la fila, con el evento clic
        int fila=TabLista.rowAtPoint(evt.getPoint());
        Logica.ClsAlumno alum=new Logica.ClsAlumno();
        //Captura de los datos de la alumno para editarlo
         this.idalumno=Integer.parseInt(TabLista.getValueAt(fila, 0).toString());
         this.TxtNombres.setText(TabLista.getValueAt(fila, 2).toString());
         this.TxtApellidos.setText(TabLista.getValueAt(fila, 1).toString());
         this.TxtDireccion.setText(TabLista.getValueAt(fila, 5).toString());
         this.TxtTelefono.setText(TabLista.getValueAt(fila, 6).toString());
         this.TxtEmail.setText(TabLista.getValueAt(fila, 7).toString());
         this.TxtPassword.setText(TabLista.getValueAt(fila, 8).toString());
         this.CBXGrado.setSelectedItem(TabLista.getValueAt(fila, 9).toString());
         this.CBXSeccion.setSelectedItem(TabLista.getValueAt(fila, 10).toString());
         //captura la fecha y le da formato correcto Dia,mes,año
         /*String dia=TabLista.getValueAt(fila, 3).toString().substring(8, 10);
         String mes=TabLista.getValueAt(fila, 3).toString().substring(5, 7);
         String anio=TabLista.getValueAt(fila, 3).toString().substring(0, 4);
         String FECHA=""+dia+"/"+mes+"/"+anio;*/
         
         this.TxtFecha.setText((String) TabLista.getValueAt(fila, 3));
       
         //Captura de los datos para el Radio Buton Sexo
       if (TabLista.getValueAt(fila, 4).toString().equals("Masculino")){
           this.RBMasculino.setSelected(true);
       }else
            this.RBFemenino.setSelected(true);        
    }//GEN-LAST:event_TabListaMouseClicked

    private void CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseEntered

    private void CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseExited

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JComboBox<String> CBXGrado;
    private javax.swing.JComboBox<String> CBXSeccion;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JRadioButton RBFemenino;
    private javax.swing.JRadioButton RBMasculino;
    private javax.swing.JButton Registrar;
    private javax.swing.JTable TabLista;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
/**Métodos Auxiliares*/
    private void ListarAlumnos(){ //Cargamos la tabla con la lista de personas
         //Creamos un objeto alumno
        Logica.ClsAlumno alumno=new Logica.ClsAlumno();
        //Creamos un modelo de tabla
        TableModel modelo = new DefaultTableModel();
        //Extraemos la lista de personas dentro de un modelo
        modelo=alumno.ListarAlumnos();

        //Asociamos el modelo al JTable
        this.TabLista.setModel(modelo);
        
        //Oculta la primera columna
        OcultarColumnaTabla();
    }

    public void Limpiarcampos(){
       this.CBXGrado.setSelectedIndex(0);
       this.TxtNombres.setText("");
       this.TxtApellidos.setText("");
       this.TxtDireccion.setText("");
       this.TxtTelefono.setText("");
       this.TxtEmail.setText("");
       this.TxtPassword.setText("");
       this.TxtFecha.setText("");
    }
    
    private  void OcultarColumnaTabla(){
            //Oculta la primera columna de la tabla
       this.TabLista.getColumnModel().getColumn(0).setMaxWidth(0);
       this.TabLista.getColumnModel().getColumn(0).setMinWidth(0);
       this.TabLista. getColumnModel().getColumn(0).setPreferredWidth(0);
       
       
       
       this.TabLista.getColumnModel().getColumn(7).setMaxWidth(0);
       this.TabLista.getColumnModel().getColumn(7).setMinWidth(0);
       this.TabLista. getColumnModel().getColumn(7).setPreferredWidth(0);
       
       
       
       
       this.TabLista.getColumnModel().getColumn(8).setMaxWidth(0);
       this.TabLista.getColumnModel().getColumn(8).setMinWidth(0);
       this.TabLista. getColumnModel().getColumn(8).setPreferredWidth(0);
    }

}
