/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alksystem;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author HDMS PC
 */
public class menu extends javax.swing.JFrame {

   

    /**
     * Creates new form login
     */
    public menu(){
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        save2 = new javax.swing.JButton();
        curso = new javax.swing.JButton();
        save = new javax.swing.JButton();
        save3 = new javax.swing.JButton();
        save4 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(13, 152, 242));

        jLabel5.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MENU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setBackground(new Color(0,0,0,0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        jButton1.setToolTipText("SALIR");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(134, 114));
        jButton1.setPreferredSize(new java.awt.Dimension(134, 114));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        save2.setBackground(new Color(0,0,0,0));
        save2.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        save2.setForeground(new java.awt.Color(255, 255, 255));
        save2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        save2.setToolTipText("ESTUDIANTE");
        save2.setActionCommand("ACEPTAR");
        save2.setBorderPainted(false);
        save2.setContentAreaFilled(false);
        save2.setFocusPainted(false);
        save2.setMaximumSize(new java.awt.Dimension(134, 114));
        save2.setPreferredSize(new java.awt.Dimension(134, 114));
        save2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save2MouseExited(evt);
            }
        });
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });

        curso.setBackground(new Color(0,0,0,0));
        curso.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        curso.setForeground(new java.awt.Color(255, 255, 255));
        curso.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/course.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        curso.setToolTipText("CURSO");
        curso.setActionCommand("ACEPTAR");
        curso.setBorderPainted(false);
        curso.setContentAreaFilled(false);
        curso.setFocusPainted(false);
        curso.setMaximumSize(new java.awt.Dimension(134, 114));
        curso.setPreferredSize(new java.awt.Dimension(134, 114));
        curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cursoMouseExited(evt);
            }
        });
        curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoActionPerformed(evt);
            }
        });

        save.setBackground(new Color(0,0,0,0));
        save.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/teacher.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        save.setToolTipText("PROFESOR");
        save.setActionCommand("ACEPTAR");
        save.setBorderPainted(false);
        save.setContentAreaFilled(false);
        save.setFocusPainted(false);
        save.setMaximumSize(new java.awt.Dimension(134, 114));
        save.setPreferredSize(new java.awt.Dimension(134, 114));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        save3.setBackground(new Color(0,0,0,0));
        save3.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        save3.setForeground(new java.awt.Color(255, 255, 255));
        save3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        save3.setToolTipText("LOGOUT");
        save3.setActionCommand("ACEPTAR");
        save3.setBorderPainted(false);
        save3.setContentAreaFilled(false);
        save3.setFocusPainted(false);
        save3.setMaximumSize(new java.awt.Dimension(134, 114));
        save3.setPreferredSize(new java.awt.Dimension(134, 114));
        save3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save3MouseExited(evt);
            }
        });
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });

        save4.setBackground(new Color(0,0,0,0));
        save4.setFont(new java.awt.Font("Freestyle Script", 1, 18)); // NOI18N
        save4.setForeground(new java.awt.Color(255, 255, 255));
        save4.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png")).getImage().getScaledInstance(80,80, Image.SCALE_SMOOTH)));
        save4.setToolTipText("INFO");
        save4.setActionCommand("ACEPTAR");
        save4.setBorderPainted(false);
        save4.setContentAreaFilled(false);
        save4.setFocusPainted(false);
        save4.setMaximumSize(new java.awt.Dimension(134, 114));
        save4.setPreferredSize(new java.awt.Dimension(134, 114));
        save4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save4MouseExited(evt);
            }
        });
        save4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(save3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(save2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(save4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(curso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx=0;
    int yy=0;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //        // TODO add your handling code here:
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_saveMouseExited

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_saveMouseEntered

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        maestro prof = new maestro();
        prof.setVisible(true);
        prof.setLocationRelativeTo(null);
        prof.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.dispose();
        
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void cursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoMouseEntered

    private void cursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoMouseExited

    private void cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoActionPerformed
       
        cursos CUR = new cursos();
        CUR.setVisible(true);
        CUR.setLocationRelativeTo(null);
        CUR.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.dispose();
    }//GEN-LAST:event_cursoActionPerformed

    private void save2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseEntered

    private void save2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_save2MouseExited

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        // TODO add your handling code here:
        estudiante EST = new estudiante();
        EST.setVisible(true);
        EST.setLocationRelativeTo(null);
        EST.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.dispose();
    }//GEN-LAST:event_save2ActionPerformed

    private void save3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseEntered

    private void save3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_save3MouseExited

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
        // TODO add your handling code here:
        login LOG = new login();
        LOG.setVisible(true);
        LOG.setLocationRelativeTo(null);
        LOG.setBackground(new Color(1.0f,1.0f,1.0f,0.0f));
        this.dispose();
        
    }//GEN-LAST:event_save3ActionPerformed

    private void save4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_save4MouseEntered

    private void save4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_save4MouseExited

    private void save4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save4ActionPerformed
        // TODO add your handling code here:
        
        acercade acd= new acercade();
        acd.setVisible(true);
        acd.setLocationRelativeTo(null);
    }//GEN-LAST:event_save4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton save;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    private javax.swing.JButton save4;
    // End of variables declaration//GEN-END:variables
}
